---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - { title: "Home", href: "index.html", align: right }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(dplyr)
library(plotly)
data("instacart")
produce_instacart = instacart |> filter(department == "produce")
```

Column {data-width=500}
-----------------------------------------------------------------------

### Top 10 most ordered products in the produce department

```{r}
produce_instacart |> 
  count(product_name) |> 
  arrange(desc(n)) |> 
  head(10) |> 
  mutate(product_name = fct_reorder(product_name, n, .desc = TRUE)) |> 
  plot_ly(x = ~product_name, y = ~n, 
          color = ~product_name, 
          type = "bar", colors = "viridis") |> 
  layout(title = "Top 10 most ordered products in the produce department",
         xaxis = list(title = "Product Name"),
         yaxis = list(title = "Number of times ordered"))
```

Column {data-width=500}
-----------------------------------------------------------------------

### Number of produce order per day

```{r}
produce_instacart |> 
  group_by(order_dow) |> 
  count(aisle) |> 
  plot_ly(y = ~n, color = ~aisle, type = "box", colors = "viridis") |> 
  layout(title = "Number of products order for each aisle in produce department per day",
         yaxis = list(title = "Number of order"))
```

### Number of Produce order by hour

```{r}
produce_instacart |> 
  group_by(order_hour_of_day) |> 
  count(aisle) |> 
  plot_ly(x = ~order_hour_of_day, y = ~n, 
          type = "scatter", mode = "markers", 
          name = ~aisle) |> 
  layout(title = "Number of Produce order from each aisle in a day",
         xaxis = list(title = "Hour of day"),
         yaxis = list(title = "Number of order"))
```